### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by zaovb** [billthefarmer/ctuner#3]
Excuse me, I was trying to install this app on my Linux distribution, but I was not able to find the way to do it.

Maybe you can answer me how to do it and add it to the README archive.

Thanks!

Edit: Excuse me, I though the INSTALL doc was a script or something.

I'm not able to install it anyway.

**Comment by billthefarmer** [comment]
To install on linux, just copy the binary to `/usr/local/bin` after you have built it. I found a deliberate mistake in the downsampling code last month and haven't got around to making a new release. So to get the latest fixed version, either download a zip from the repo front page, not releases, or clone it, make sure you have the prerequisites `gtk+-3`, and `alsa` and run `make`.
```shell
pi@catherine:~ $ git clone https://github.com/billthefarmer/ctuner.git
Cloning into 'ctuner'...
remote: Enumerating objects: 2816, done.
remote: Counting objects: 100% (332/332), done.
remote: Compressing objects: 100% (220/220), done.
remote: Total 2816 (delta 210), reused 185 (delta 99), pack-reused 2484
Receiving objects: 100% (2816/2816), 25.05 MiB | 1.88 MiB/s, done.
Resolving deltas: 100% (1797/1797), done.
pi@catherine:~ $ cd ctuner/linux/
pi@catherine:~/ctuner/linux $ make
g++ tuner.cpp -o tuner -O -fPIC -Wl,-z,relro -Wall -lX11 -lasound -lm \
        `pkg-config --cflags --libs gtk+-3.0`
pi@catherine:~/ctuner/linux $ sudo cp tuner /usr/local/bin/
pi@catherine:~/ctuner/linux $ tuner
Unable to init server: Could not connect: Connection refused

(tuner:21813): Gtk-WARNING **: 08:44:14.906: cannot open display:
```
This is on my pi which doesn't have a display, or an audio input, but it builds.

**Comment by zaovb** [comment]
Amazing!

Your tuner is the best out there, for sure. Know it!
