### ISSUE TITLE
Provide no-install version?

### ISSUE THREAD

**Issue by sdasda7777** [billthefarmer/ctuner#5]
Hey, would it be possible to provide no-install ("portable") version along with the other builds?
I'm sure I'm not the only one feeling bit uneasy about running a file downloaded from the internet with admin privileges.
Otherwise it looks really nice, thank you so much.

**Comment by billthefarmer** [comment]
`Tuner.exe` can be extracted from the installer using an archive tool like [7-Zip](https://www.7-zip.org/index.html).

**Comment by sdasda7777** [comment]
I still think providing the executable in a zip file would be nice (since the install exe is not a zip file, and not everyone has an archiving tool installed), but I guess this works too, thanks.

**Comment by sdasda7777** [comment]
Oh, I just noticed you did just that. Thanks again.
