### ISSUE TITLE
Ctuner 1.08 crashes at startup on latest MacOS

### ISSUE THREAD

**Issue by dotfiles-n-stuff** [billthefarmer/ctuner#6]
After updating to Ventura 13.1 (22C65) ctuner refuses to launch. Been working fine before OS update though. Here's the crash log:

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Tuner [12815]
Path:                  /Applications/Tuner.app/Contents/MacOS/Tuner
Identifier:            org.billthefarmer.Tuner
Version:               1.08 (1.08)
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-12-17 23:03:51.8050 +0300
OS Version:            macOS 13.1 (22C65)
Report Version:        12
Anonymous UUID:        F525D27A-A056-04A6-2F95-0360CE78889F

Sleep/Wake UUID:       A227613E-4BA5-485F-A93F-8E08C4627076

Time Awake Since Boot: 47000 seconds
Time Since Wake:       1678 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 4 Illegal instruction: 4
Terminating Process:   exc handler [12815]

Kernel Triage:
VM - pmap_enter retried due to resource shortage
VM - pmap_enter retried due to resource shortage

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libswiftCore.dylib            	       0x10b59f941 specialized _fatalErrorMessage(_:_:file:line:flags:) + 113
1   libswiftCore.dylib            	       0x10b3d6c23 _fatalErrorMessage(_:_:file:line:flags:) + 19
2   Tuner                         	       0x102444b88 AppDelegate.applicationDidFinishLaunching(_:) + 2808
3   Tuner                         	       0x10244872c @objc AppDelegate.applicationDidFinishLaunching(_:) + 76
4   CoreFoundation                	    0x7ff80fc516d6 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 137
5   CoreFoundation                	    0x7ff80fceacbc ___CFXRegistrationPost_block_invoke + 86
6   CoreFoundation                	    0x7ff80fceac13 _CFXRegistrationPost + 534
7   CoreFoundation                	    0x7ff80fc24e31 _CFXNotificationPost + 809
8   Foundation                    	    0x7ff810999f2c -[NSNotificationCenter postNotificationName:object:userInfo:] + 82
9   AppKit                        	    0x7ff812ce8c74 -[NSApplication _postDidFinishNotification] + 305
10  AppKit                        	    0x7ff812ce89c6 -[NSApplication _sendFinishLaunchingNotification] + 208
11  AppKit                        	    0x7ff812ce66f2 -[NSApplication(NSAppleEventHandling) _handleAEOpenEvent:] + 541
12  AppKit                        	    0x7ff812ce6348 -[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:] + 665
13  Foundation                    	    0x7ff8109c4d24 -[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:] + 308
14  Foundation                    	    0x7ff8109c4b96 _NSAppleEventManagerGenericHandler + 80
15  AE                            	    0x7ff816160d9d 0x7ff816155000 + 48541
16  AE                            	    0x7ff816160608 0x7ff816155000 + 46600
17  AE                            	    0x7ff816159c1d aeProcessAppleEvent + 419
18  HIToolbox                     	    0x7ff819af4e3f AEProcessAppleEvent + 54
19  AppKit                        	    0x7ff812ce1270 _DPSNextEvent + 1738
20  AppKit                        	    0x7ff812cdfdb4 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1219
21  AppKit                        	    0x7ff812cd23f7 -[NSApplication run] + 586
22  AppKit                        	    0x7ff812ca6427 NSApplicationMain + 817
23  Tuner                         	       0x102459fcd main + 13
24  dyld                          	       0x2028d4310 start + 2432

Thread 1:: com.apple.rosetta.exceptionserver
0   runtime                       	    0x7ff7ffdf4614 0x7ff7ffdf0000 + 17940
1   runtime                       	    0x7ff7ffe00530 0x7ff7ffdf0000 + 66864
2   runtime                       	    0x7ff7ffe01f30 0x7ff7ffdf0000 + 73520

Thread 2:
0   runtime                       	    0x7ff7ffe1287c 0x7ff7ffdf0000 + 141436

Thread 3:
0   runtime                       	    0x7ff7ffe1287c 0x7ff7ffdf0000 + 141436

Thread 4:
0   runtime                       	    0x7ff7ffe1287c 0x7ff7ffdf0000 + 141436

Thread 5:
0   runtime                       	    0x7ff7ffe1287c 0x7ff7ffdf0000 + 141436

Thread 6:
0   runtime                       	    0x7ff7ffe1287c 0x7ff7ffdf0000 + 141436

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x000000009269482b  rbx: 0x00000001024a4a60  rcx: 0x0000000000000002  rdx: 0x000000009289502c
  rdi: 0x0000000092895000  rsi: 0x000000000000002b  rbp: 0x0000000308e041a0  rsp: 0x0000000308e04160
   r8: 0x0000000000000155   r9: 0x0000000000000154  r10: 0x0000000000000810  r11: 0x0000600002e9e988
  r12: 0x00000001024a4a9a  r13: 0x00006000022a4810  r14: 0x0000000000000002  r15: 0x0000000000000039
  rip: <unavailable>       rfl: 0x0000000000000202
 tmp0: 0x000000010b59f941 tmp1: 0x0000000000000214 tmp2: 0x000000010bda6608

Binary Images:
       0x10b375000 -        0x10b707fff libswiftCore.dylib (*) <d0c86227-bfc8-30d7-93b8-9f228e0f15ba> /Applications/Tuner.app/Contents/Frameworks/libswiftCore.dylib
       0x102441000 -        0x1024a8fff org.billthefarmer.Tuner (1.08) <f3160906-f1c3-3b40-a411-561c96359db5> /Applications/Tuner.app/Contents/MacOS/Tuner
    0x7ff80fbdd000 -     0x7ff810074fff com.apple.CoreFoundation (6.9) <f3846a86-644b-3bcd-acce-fc7b751105c1> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7ff810990000 -     0x7ff8113a1ff6 com.apple.Foundation (6.9) <ab5f8db8-b03b-33b6-98f7-ffaec27a8eab> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7ff812ca3000 -     0x7ff813caafff com.apple.AppKit (6.9) <00f4aa78-a19f-3a8e-9650-9f90b7beefd6> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7ff816155000 -     0x7ff8161c4fff com.apple.AE (946) <769381c9-e6f5-3dfc-9b8b-2810b71a487e> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE
    0x7ff819ab4000 -     0x7ff819dabffd com.apple.HIToolbox (2.1.1) <db45022f-3922-35b3-9a06-377f66ed0fbe> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
       0x2028ce000 -        0x202965fff dyld (*) <bb7a0970-8c62-3dce-a7a2-5cec9c501f11> /usr/lib/dyld
    0x7ff7ffdf0000 -     0x7ff7ffe1ffff runtime (*) <d592bc4a-4a21-348f-a406-e12f9cd2f27c> /usr/libexec/rosetta/runtime

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=407.0M resident=0K(0%) swapped_out_or_unallocated=407.0M(100%)
Writable regions: Total=1.2G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.2G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               128K        1 
Activity Tracing                   256K        1 
CG backing stores                 2176K        4 
CG image                            36K        3 
ColorSync                          224K       25 
CoreAnimation                       44K        6 
CoreGraphics                        12K        2 
CoreUI image data                  844K        6 
Foundation                          16K        1 
Kernel Alloc Once                    8K        1 
MALLOC                           209.2M       34 
MALLOC guard page                  192K        9 
MALLOC_MEDIUM (reserved)         480.0M        4         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
Rosetta Arena                     4096K        2 
Rosetta Generic                   1084K      268 
Rosetta IndirectBranch             512K        1 
Rosetta JIT                      128.0M        1 
Rosetta Return Stack               120K       12 
Rosetta Thread Context             120K       12 
STACK GUARD                         20K        5 
Stack                             10.6M        6 
Stack Guard                       56.0M        1 
VM_ALLOCATE                       9612K       22 
VM_ALLOCATE (reserved)              72K       16         reserved VM address space (unallocated)
__CTF                               756        1 
__DATA                            17.4M      331 
__DATA_CONST                      13.9M      182 
__DATA_DIRTY                       661K      107 
__FONT_DATA                        2352        1 
__LINKEDIT                       172.4M       27 
__OBJC_RO                         65.4M        1 
__OBJC_RW                         1985K        2 
__TEXT                           234.7M      345 
dyld private memory                256K        1 
mapped file                        4.2G     1303 
shared memory                      808K       16 
unshared pmap                     6272K        4 
===========                     =======  ======= 
TOTAL                              5.9G     2765 
TOTAL, minus reserved VM space     5.1G     2765 

-----------
Full Report
-----------

{"app_name":"Tuner","timestamp":"2022-12-17 23:03:52.00 +0300","app_version":"1.08","slice_uuid":"f3160906-f1c3-3b40-a411-561c96359db5","build_version":"1.08","platform":1,"bundleID":"org.billthefarmer.Tuner","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.1 (22C65)","roots_installed":0,"name":"Tuner","incident_id":"ADFCFA28-9EAD-4A83-A3AD-A0671F068FB0"}
{
  "uptime" : 47000,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookAir10,1",
  "coalitionID" : 1236,
  "osVersion" : {
    "train" : "macOS 13.1",
    "build" : "22C65",
    "releaseType" : "User"
  },
  "captureTime" : "2022-12-17 23:03:51.8050 +0300",
  "incident" : "ADFCFA28-9EAD-4A83-A3AD-A0671F068FB0",
  "pid" : 12815,
  "translated" : true,
  "cpuType" : "X86-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2022-12-17 23:03:49.9286 +0300",
  "procStartAbsTime" : 1132901526723,
  "procExitAbsTime" : 1132946538185,
  "procName" : "Tuner",
  "procPath" : "\/Applications\/Tuner.app\/Contents\/MacOS\/Tuner",
  "bundleInfo" : {"CFBundleShortVersionString":"1.08","CFBundleVersion":"1.08","CFBundleIdentifier":"org.billthefarmer.Tuner"},
  "storeInfo" : {"deviceIdentifierForVendor":"D4586F52-ED4D-5CAC-9F06-A8A53A24C0FB","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "org.billthefarmer.Tuner",
  "crashReporterKey" : "F525D27A-A056-04A6-2F95-0360CE78889F",
  "throttleTimeout" : 2147483647,
  "wakeTime" : 1678,
  "sleepWakeUUID" : "A227613E-4BA5-485F-A93F-8E08C4627076",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000001, 0x0000000000000000","rawCodes":[1,0],"type":"EXC_BAD_INSTRUCTION","signal":"SIGILL"},
  "termination" : {"flags":0,"code":4,"namespace":"SIGNAL","indicator":"Illegal instruction: 4","byProc":"exc handler","byPid":12815},
  "ktriageinfo" : "VM - pmap_enter retried due to resource shortage\nVM - pmap_enter retried due to resource shortage\n",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":353731,"threadState":{"flavor":"x86_THREAD_STATE","rbp":{"value":13033816480},"r12":{"value":4333390490},"rosetta":{"tmp2":{"value":4493829640},"tmp1":{"value":532},"tmp0":{"value":4485413185}},"rbx":{"value":4333390432},"r8":{"value":341},"r15":{"value":57},"r10":{"value":2064},"rdx":{"value":2458472492},"rdi":{"value":2458472448},"r9":{"value":340},"r13":{"value":105553152591888},"rflags":{"value":514},"rax":{"value":2456373291},"rsp":{"value":13033816416},"r11":{"value":105553165150600},"rcx":{"value":2},"r14":{"value":2},"rsi":{"value":43}},"queue":"com.apple.main-thread","frames":[{"imageOffset":2271553,"symbol":"specialized _fatalErrorMessage(_:_:file:line:flags:)","symbolLocation":113,"imageIndex":0},{"imageOffset":400419,"symbol":"_fatalErrorMessage(_:_:file:line:flags:)","symbolLocation":19,"imageIndex":0},{"imageOffset":15240,"symbol":"AppDelegate.applicationDidFinishLaunching(_:)","symbolLocation":2808,"imageIndex":1},{"imageOffset":30508,"symbol":"@objc AppDelegate.applicationDidFinishLaunching(_:)","symbolLocation":76,"imageIndex":1},{"imageOffset":476886,"symbol":"__CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__","symbolLocation":137,"imageIndex":2},{"imageOffset":1105084,"symbol":"___CFXRegistrationPost_block_invoke","symbolLocation":86,"imageIndex":2},{"imageOffset":1104915,"symbol":"_CFXRegistrationPost","symbolLocation":534,"imageIndex":2},{"imageOffset":294449,"symbol":"_CFXNotificationPost","symbolLocation":809,"imageIndex":2},{"imageOffset":40748,"symbol":"-[NSNotificationCenter postNotificationName:object:userInfo:]","symbolLocation":82,"imageIndex":3},{"imageOffset":285812,"symbol":"-[NSApplication _postDidFinishNotification]","symbolLocation":305,"imageIndex":4},{"imageOffset":285126,"symbol":"-[NSApplication _sendFinishLaunchingNotification]","symbolLocation":208,"imageIndex":4},{"imageOffset":276210,"symbol":"-[NSApplication(NSAppleEventHandling) _handleAEOpenEvent:]","symbolLocation":541,"imageIndex":4},{"imageOffset":275272,"symbol":"-[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:]","symbolLocation":665,"imageIndex":4},{"imageOffset":216356,"symbol":"-[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:]","symbolLocation":308,"imageIndex":3},{"imageOffset":215958,"symbol":"_NSAppleEventManagerGenericHandler","symbolLocation":80,"imageIndex":3},{"imageOffset":48541,"imageIndex":5},{"imageOffset":46600,"imageIndex":5},{"imageOffset":19485,"symbol":"aeProcessAppleEvent","symbolLocation":419,"imageIndex":5},{"imageOffset":265791,"symbol":"AEProcessAppleEvent","symbolLocation":54,"imageIndex":6},{"imageOffset":254576,"symbol":"_DPSNextEvent","symbolLocation":1738,"imageIndex":4},{"imageOffset":249268,"symbol":"-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]","symbolLocation":1219,"imageIndex":4},{"imageOffset":193527,"symbol":"-[NSApplication run]","symbolLocation":586,"imageIndex":4},{"imageOffset":13351,"symbol":"NSApplicationMain","symbolLocation":817,"imageIndex":4},{"imageOffset":102349,"symbol":"main","symbolLocation":13,"imageIndex":1},{"imageOffset":25360,"symbol":"start","symbolLocation":2432,"imageIndex":7}]},{"id":353799,"name":"com.apple.rosetta.exceptionserver","frames":[{"imageOffset":17940,"imageIndex":8},{"imageOffset":66864,"imageIndex":8},{"imageOffset":73520,"imageIndex":8}]},{"id":353919,"frames":[{"imageOffset":141436,"imageIndex":8}]},{"id":353920,"frames":[{"imageOffset":141436,"imageIndex":8}]},{"id":353924,"frames":[{"imageOffset":141436,"imageIndex":8}]},{"id":353930,"frames":[{"imageOffset":141436,"imageIndex":8}]},{"id":353936,"frames":[{"imageOffset":141436,"imageIndex":8}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4483141632,
    "size" : 3747840,
    "uuid" : "d0c86227-bfc8-30d7-93b8-9f228e0f15ba",
    "path" : "\/Applications\/Tuner.app\/Contents\/Frameworks\/libswiftCore.dylib",
    "name" : "libswiftCore.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4332982272,
    "CFBundleShortVersionString" : "1.08",
    "CFBundleIdentifier" : "org.billthefarmer.Tuner",
    "size" : 425984,
    "uuid" : "f3160906-f1c3-3b40-a411-561c96359db5",
    "path" : "\/Applications\/Tuner.app\/Contents\/MacOS\/Tuner",
    "name" : "Tuner",
    "CFBundleVersion" : "1.08"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703392714752,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 4816896,
    "uuid" : "f3846a86-644b-3bcd-acce-fc7b751105c1",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1953.300"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703407079424,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.Foundation",
    "size" : 10559479,
    "uuid" : "ab5f8db8-b03b-33b6-98f7-ffaec27a8eab",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Versions\/C\/Foundation",
    "name" : "Foundation",
    "CFBundleVersion" : "1953.300"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703443857408,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 16809984,
    "uuid" : "00f4aa78-a19f-3a8e-9650-9f90b7beefd6",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2299.30.116"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703499112448,
    "CFBundleShortVersionString" : "946",
    "CFBundleIdentifier" : "com.apple.AE",
    "size" : 458752,
    "uuid" : "769381c9-e6f5-3dfc-9b8b-2810b71a487e",
    "path" : "\/System\/Library\/Frameworks\/CoreServices.framework\/Versions\/A\/Frameworks\/AE.framework\/Versions\/A\/AE",
    "name" : "AE",
    "CFBundleVersion" : "946"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703559270400,
    "CFBundleShortVersionString" : "2.1.1",
    "CFBundleIdentifier" : "com.apple.HIToolbox",
    "size" : 3112958,
    "uuid" : "db45022f-3922-35b3-9a06-377f66ed0fbe",
    "path" : "\/System\/Library\/Frameworks\/Carbon.framework\/Versions\/A\/Frameworks\/HIToolbox.framework\/Versions\/A\/HIToolbox",
    "name" : "HIToolbox"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 8632721408,
    "size" : 622592,
    "uuid" : "bb7a0970-8c62-3dce-a7a2-5cec9c501f11",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 140703126454272,
    "size" : 196608,
    "uuid" : "d592bc4a-4a21-348f-a406-e12f9cd2f27c",
    "path" : "\/usr\/libexec\/rosetta\/runtime",
    "name" : "runtime"
  }
],
  "sharedCache" : {
  "base" : 140703388352512,
  "size" : 21474836480,
  "uuid" : "16923f88-e9fc-38d2-947c-df242e486636"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=407.0M resident=0K(0%) swapped_out_or_unallocated=407.0M(100%)\nWritable regions: Total=1.2G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.2G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               128K        1 \nActivity Tracing                   256K        1 \nCG backing stores                 2176K        4 \nCG image                            36K        3 \nColorSync                          224K       25 \nCoreAnimation                       44K        6 \nCoreGraphics                        12K        2 \nCoreUI image data                  844K        6 \nFoundation                          16K        1 \nKernel Alloc Once                    8K        1 \nMALLOC                           209.2M       34 \nMALLOC guard page                  192K        9 \nMALLOC_MEDIUM (reserved)         480.0M        4         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nRosetta Arena                     4096K        2 \nRosetta Generic                   1084K      268 \nRosetta IndirectBranch             512K        1 \nRosetta JIT                      128.0M        1 \nRosetta Return Stack               120K       12 \nRosetta Thread Context             120K       12 \nSTACK GUARD                         20K        5 \nStack                             10.6M        6 \nStack Guard                       56.0M        1 \nVM_ALLOCATE                       9612K       22 \nVM_ALLOCATE (reserved)              72K       16         reserved VM address space (unallocated)\n__CTF                               756        1 \n__DATA                            17.4M      331 \n__DATA_CONST                      13.9M      182 \n__DATA_DIRTY                       661K      107 \n__FONT_DATA                        2352        1 \n__LINKEDIT                       172.4M       27 \n__OBJC_RO                         65.4M        1 \n__OBJC_RW                         1985K        2 \n__TEXT                           234.7M      345 \ndyld private memory                256K        1 \nmapped file                        4.2G     1303 \nshared memory                      808K       16 \nunshared pmap                     6272K        4 \n===========                     =======  ======= \nTOTAL                              5.9G     2765 \nTOTAL, minus reserved VM space     5.1G     2765 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "610d52e1fc54bc3389840408",
      "factorPackIds" : {
        "SIRI_UNDERSTANDING_ASR_ASSISTANT" : "6376d83499e1ff5d8f0dcc3f",
        "SIRI_UNDERSTANDING_MORPHUN" : "62ec7220c682040ba94e6a20"
      },
      "deploymentId" : 240000545
    },
    {
      "rolloutId" : "62cdf63ddb3b7109d6d765cc",
      "factorPackIds" : {
        "SIRI_UNDERSTANDING_TMDC" : "62cdf6dddb3b7109d6d765cd"
      },
      "deploymentId" : 240000007
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookAir10,1, BootROM 8419.60.44, proc 8:4:4 processors, 16 GB, SMC 
Graphics: Apple M1, Apple M1, Built-In
Display: Color LCD, 2560 x 1600 Retina, Main, MirrorOff, Online
Memory Module: LPDDR4, Hynix
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4378), wl0: Sep  3 2022 03:37:22 version 18.20.379.4.7.8.143 FWID 01-e3c71b50
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Air, Apple Inc.
Thunderbolt Bus: MacBook Air, Apple Inc.

**Comment by billthefarmer** [comment]
It says at the start of your crash log that it's translated, so the dump probably doesn't help. I will have to see if I can build an x86_64/arm64 version. That should fix it.

~~I have got GitHub to build it on a more up to date system. See if this works.~~

**Comment by billthefarmer** [comment]
That probably won't work. I have successfully build this app on GitHub MacOS 11 with swift 5, but it doesn't work. I can't fix it until I can borrow the use of a more recent Mac. Probably next year. Meanwhile the current version seems to work OK on most Macs.

**Comment by dotfiles-n-stuff** [comment]
oh well.. thanks for the effort anyways. The app was excellent while it worked :)

**Comment by dotfiles-n-stuff** [comment]
Got a Korg CA-50 instead :)

**Comment by billthefarmer** [comment]
Very nice. I have managed to build a working universal app.

[Tuner-1.08.dmg.zip](https://github.com/billthefarmer/ctuner/files/11008960/Tuner-1.08.dmg.zip)
