### ISSUE TITLE
Is there a start/stop record button

### ISSUE THREAD

**Issue by shirzartenwer** [billthefarmer/ctuner#8]
Hey, thanks for this amazing work! 
I really want to use this to tune my accordion. However, when I play my accordion next to my laptop, where this software is running, I don't see anything displayed on the software. Do I need to start or stop recording somewhere?

**Comment by billthefarmer** [comment]
The app takes it's input from whatever is selected in the Settings > System > Sound > Input. There is a link to Settings > Privacy > Microphone, which should be on, and Allow desktop apps to access your microphone, further down. That is assuming you are using windows. MacOS is different, but similar.
